### ISSUE TITLE
Mathods to set up another website?

### ISSUE THREAD

**Issue by ghost** [micromaomao/schsrch#1]
I wanna setup another website using ur code, but is there a set up guide, or some engine reqirement?
PS: I am now using this website for papers. Wish you have a good mark  in May!

**Comment by micromaomao** [comment]
Well…
The code is (initially) written without taking much reuseability into consideration. I run it on my server as a plugin to my [home page](https://github.com/micromaomao/maowtm.org), but I think it is certainly possible to run it in a simple, standalone node environment.

You will need to run node 9 on your server, as well as mongodb and elasticsearch. `index.js` contains a function that takes in an object `{mongodb, elasticsearch}` which is the connection instance, and returns an express router, but there is no written code in this project (yet) to do the bootstrapping thing such as setting up express and connecting to db. (Those are done, on my server, by [this](https://github.com/micromaomao/maowtm.org/blob/master/index.js), but you probably don't want to run that.)

If you don't have any experience with developing with node or you failed to understand what I just said, feel free to reply here or send me email - my address is [m@maowtm.org](mailto:m@maowtm.org). I'm glad to help you.

By the way, I'm happy to help you no matter what but I would like to know why are you trying to run another instance of this? Do you have some special requirements that may require some re-programming, or do you want to use it for other examinations?

**Comment by micromaomao** [comment]
BTW, I sense that you are a Chinese…

我看得懂也会说中文【不过要用英文也很乐意的- -

**Comment by ghost** [comment]
# Great!
Yes you r right, that i am truely a chinese.....
不知道为什么习惯了在这里说英文
Well, I initially just wanted to learn some web develop, (and now what i can do is only develop API.....), I want some fantastic examples of foreground designing.
The method i used to learn a new language is to "change" something and see what different things the program show to me, 
yep, these above,  are the SIMPLE reason for my ask for re-distribution.

#Added: LAter today, after i finished my h.....homework

**Comment by micromaomao** [comment]
【前端叫*front-end*, 不是foreground

Well... This project is not well-suited for beginners trying to learn front-end development for varies reasons. It use webpack, which is kind of a complicated way to transform and minify javascript. There is no CSS and HTML, I use [sass](https://sass-lang.com/) and a bit of [pug](https://pugjs.org/), and most of the UI is made with [React](https://reactjs.org/). A peak into [some](https://github.com/micromaomao/schsrch/blob/master/view/layout.sass) [of](https://github.com/micromaomao/schsrch/blob/master/view/index.pug) [the](https://github.com/micromaomao/schsrch/blob/master/view/schsrch.jsx#L242) [code](https://github.com/micromaomao/schsrch/blob/master/view/serverrender.jsx) should prove my point.

In addition, [some c++ code in this project](https://github.com/micromaomao/schsrch/blob/master/src/sspdf.cc) that take care of inspecting PDFs makes me uncertain that it will run on Windows.

But I didn't meant to discourage you! If you are new to front-end design, maybe you should find some other examples to play with, or you could try to follow some of the tutorials available online. If you already have good skill on HTML, CSS or Javascript, I found it helpful for learning trying to reproduce the interface of other websites from scratch, or simply build your own web page for any purpose.

**Comment by ghost** [comment]
OK, Well then I will find another source of lerning😄
BTW, Great thanks.
