### ISSUE TITLE
Expired SSL Cert on schsrch.xyz

### ISSUE THREAD

**Issue by Yakultie** [micromaomao/schsrch#5]
Your "Let's Encrypt" SSL Cert for schsrch.xyz just expired so nobody can visit the site, as it uses HSTS. 

You might want to switch to other SSL Cert providers, or you'll have to renew every 3 months or so.

**Comment by micromaomao** [comment]
Oh, totally forgot about renewing that, thanks for reminding!

**Comment by micromaomao** [comment]
Renewed, thanks again for letting me know!

**Comment by Yakultie** [comment]
No problem. Do you have any idea when the IGCSE s18 papers will be out?

**Comment by micromaomao** [comment]
probably around the beginning of September, but I'm not sure.

**Comment by Yakultie** [comment]
Okay, thanks bro!
