### ISSUE TITLE
Problems about loading past-paper on the website

### ISSUE THREAD

**Issue by patr1ckzhu** [micromaomao/schsrch#7]
网站加载不出试卷了?
换了几个设备都没有用, 啥情况...

**Comment by micromaomao** [comment]
Done, deploying after CI run successes. (approx. 10 minute)

**Comment by micromaomao** [comment]
Thanks for reporting! Due to all sort of stuff recently, and also that I have no use for CIE past papers anymore, problem might go unnoticed for a long time. Sorry for the wait.
